title: Vega Propulsion Lab Wiki
description: Wiki Page that consist all of the development and research conducted by Vega Propulsion Lab.
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

baseurl: "wiki.vegapropulsionlab.org"
url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
